FROM apache/airflow:2.10.5

ENV TZ=Europe/Moscow

RUN pip install "apache-airflow==${AIRFLOW_VERSION}" apache-airflow-providers-postgres==5.5.2
RUN pip install "apache-airflow==${AIRFLOW_VERSION}" apache-airflow-providers-telegram

COPY ./app/secret/variables.json /opt/airflow/variables.json
COPY ./DockerBuild/AirFlow/init_airflow/connections.sh /opt/airflow/connections.sh