-- GisMeteo

CREATE TABLE prom.t_moscow_gismeteo (
 "date" date NOT NULL,
 day1 int4 NULL,
 day2 int4 NULL,
 day3 int4 NULL,
 day4 int4 NULL,
 day5 int4 NULL,
 day6 int4 NULL,
 day7 int4 NULL,
 day8 int4 NULL,
 day9 int4 NULL,
 day10 int4 NULL,
 night1 int4 NULL,
 night2 int4 NULL,
 night3 int4 NULL,
 night4 int4 NULL,
 night5 int4 NULL,
 night6 int4 NULL,
 night7 int4 NULL,
 night8 int4 NULL,
 night9 int4 NULL,
 night10 int4 NULL,
 weather1 varchar(255) NULL,
 weather2 varchar(255) NULL,
 weather3 varchar(255) NULL,
 weather4 varchar(255) NULL,
 weather5 varchar(255) NULL,
 weather6 varchar(255) NULL,
 weather7 varchar(255) NULL,
 weather8 varchar(255) NULL,
 weather9 varchar(255) NULL,
 weather10 varchar(255) NULL,
 CONSTRAINT moscow_gismeteo_pkey PRIMARY KEY (date)
);

CREATE TABLE prom.t_ekaterinburg_gismeteo (
 "date" date NOT NULL,
 day1 int4 NULL,
 day2 int4 NULL,
 day3 int4 NULL,
 day4 int4 NULL,
 day5 int4 NULL,
 day6 int4 NULL,
 day7 int4 NULL,
 day8 int4 NULL,
 day9 int4 NULL,
 day10 int4 NULL,
 night1 int4 NULL,
 night2 int4 NULL,
 night3 int4 NULL,
 night4 int4 NULL,
 night5 int4 NULL,
 night6 int4 NULL,
 night7 int4 NULL,
 night8 int4 NULL,
 night9 int4 NULL,
 night10 int4 NULL,
 weather1 varchar(255) NULL,
 weather2 varchar(255) NULL,
 weather3 varchar(255) NULL,
 weather4 varchar(255) NULL,
 weather5 varchar(255) NULL,
 weather6 varchar(255) NULL,
 weather7 varchar(255) NULL,
 weather8 varchar(255) NULL,
 weather9 varchar(255) NULL,
 weather10 varchar(255) NULL,
 CONSTRAINT ekaterinburg_gismeteo_pkey PRIMARY KEY (date)
);

CREATE TABLE prom.t_krasnodar_gismeteo (
 "date" date NOT NULL,
 day1 int4 NULL,
 day2 int4 NULL,
 day3 int4 NULL,
 day4 int4 NULL,
 day5 int4 NULL,
 day6 int4 NULL,
 day7 int4 NULL,
 day8 int4 NULL,
 day9 int4 NULL,
 day10 int4 NULL,
 night1 int4 NULL,
 night2 int4 NULL,
 night3 int4 NULL,
 night4 int4 NULL,
 night5 int4 NULL,
 night6 int4 NULL,
 night7 int4 NULL,
 night8 int4 NULL,
 night9 int4 NULL,
 night10 int4 NULL,
 weather1 varchar(255) NULL,
 weather2 varchar(255) NULL,
 weather3 varchar(255) NULL,
 weather4 varchar(255) NULL,
 weather5 varchar(255) NULL,
 weather6 varchar(255) NULL,
 weather7 varchar(255) NULL,
 weather8 varchar(255) NULL,
 weather9 varchar(255) NULL,
 weather10 varchar(255) NULL,
 CONSTRAINT krasnodar_gismeteo_pkey PRIMARY KEY (date)
);

-- Yandex

CREATE TABLE prom.t_moscow_yandex (
 "date" date NOT NULL,
 day1 int4 NULL,
 day2 int4 NULL,
 day3 int4 NULL,
 day4 int4 NULL,
 day5 int4 NULL,
 day6 int4 NULL,
 day7 int4 NULL,
 day8 int4 NULL,
 day9 int4 NULL,
 day10 int4 NULL,
 night1 int4 NULL,
 night2 int4 NULL,
 night3 int4 NULL,
 night4 int4 NULL,
 night5 int4 NULL,
 night6 int4 NULL,
 night7 int4 NULL,
 night8 int4 NULL,
 night9 int4 NULL,
 night10 int4 NULL,
 weather1 varchar(255) NULL,
 weather2 varchar(255) NULL,
 weather3 varchar(255) NULL,
 weather4 varchar(255) NULL,
 weather5 varchar(255) NULL,
 weather6 varchar(255) NULL,
 weather7 varchar(255) NULL,
 weather8 varchar(255) NULL,
 weather9 varchar(255) NULL,
 weather10 varchar(255) NULL,
 CONSTRAINT moscow_yandex_pkey PRIMARY KEY (date)
);

CREATE TABLE prom.t_ekaterinburg_yandex (
 "date" date NOT NULL,
 day1 int4 NULL,
 day2 int4 NULL,
 day3 int4 NULL,
 day4 int4 NULL,
 day5 int4 NULL,
 day6 int4 NULL,
 day7 int4 NULL,
 day8 int4 NULL,
 day9 int4 NULL,
 day10 int4 NULL,
 night1 int4 NULL,
 night2 int4 NULL,
 night3 int4 NULL,
 night4 int4 NULL,
 night5 int4 NULL,
 night6 int4 NULL,
 night7 int4 NULL,
 night8 int4 NULL,
 night9 int4 NULL,
 night10 int4 NULL,
 weather1 varchar(255) NULL,
 weather2 varchar(255) NULL,
 weather3 varchar(255) NULL,
 weather4 varchar(255) NULL,
 weather5 varchar(255) NULL,
 weather6 varchar(255) NULL,
 weather7 varchar(255) NULL,
 weather8 varchar(255) NULL,
 weather9 varchar(255) NULL,
 weather10 varchar(255) NULL,
 CONSTRAINT ekaterinburg_yandex_pkey PRIMARY KEY (date)
);

CREATE TABLE prom.t_krasnodar_yandex (
 "date" date NOT NULL,
 day1 int4 NULL,
 day2 int4 NULL,
 day3 int4 NULL,
 day4 int4 NULL,
 day5 int4 NULL,
 day6 int4 NULL,
 day7 int4 NULL,
 day8 int4 NULL,
 day9 int4 NULL,
 day10 int4 NULL,
 night1 int4 NULL,
 night2 int4 NULL,
 night3 int4 NULL,
 night4 int4 NULL,
 night5 int4 NULL,
 night6 int4 NULL,
 night7 int4 NULL,
 night8 int4 NULL,
 night9 int4 NULL,
 night10 int4 NULL,
 weather1 varchar(255) NULL,
 weather2 varchar(255) NULL,
 weather3 varchar(255) NULL,
 weather4 varchar(255) NULL,
 weather5 varchar(255) NULL,
 weather6 varchar(255) NULL,
 weather7 varchar(255) NULL,
 weather8 varchar(255) NULL,
 weather9 varchar(255) NULL,
 weather10 varchar(255) NULL,
 CONSTRAINT krasnodar_yandex_pkey PRIMARY KEY (date)
);

-- all_users
CREATE TABLE prom.all_users (
 id_users serial4 NOT NULL,
 id int4 NOT NULL,
 username varchar(45) NOT NULL,
 "date" date NOT NULL,
 CONSTRAINT all_users_id_key UNIQUE (id),
 CONSTRAINT all_users_pkey PRIMARY KEY (id_users)
);

CREATE TABLE prom.subscribers (
 id_subscribers serial4 NOT NULL,
 id int4 NOT NULL,
 "date" date NOT NULL,
 city varchar(45) NOT NULL,
 CONSTRAINT subscribers_id_key UNIQUE (id),
 CONSTRAINT subscribers_pkey PRIMARY KEY (id_subscribers)
);

ALTER TABLE prom.subscribers ADD CONSTRAINT fk_all_users FOREIGN KEY (id) REFERENCES prom.all_users(id) ON DELETE CASCADE ON UPDATE CASCADE;

-- metrics

CREATE TABLE metrics.model_moscow (
"date" DATE NOT NULL,
loss REAL,
mse REAL,
r2 REAL,
rmse REAL,
CONSTRAINT model_moscow_pkey PRIMARY KEY (date)
);

CREATE TABLE metrics.model_krasnodar (
"date" DATE NOT NULL,
loss REAL,
mse REAL,
r2 REAL,
rmse REAL,
CONSTRAINT model_krasnodar_pkey PRIMARY KEY (date)
);

CREATE TABLE metrics.model_ekaterinburg (
"date" DATE NOT NULL,
loss REAL,
mse REAL,
r2 REAL,
rmse REAL,
CONSTRAINT model_ekaterinburg_pkey PRIMARY KEY (date)
);

-- forecast

CREATE TABLE predict.forecast_moscow (
 "date" date NOT NULL,
 day1 int4 NULL,
 day2 int4 NULL,
 day3 int4 NULL,
 day4 int4 NULL,
 day5 int4 NULL,
 day6 int4 NULL,
 day7 int4 NULL,
 day8 int4 NULL,
 day9 int4 NULL,
 day10 int4 NULL,
 night1 int4 NULL,
 night2 int4 NULL,
 night3 int4 NULL,
 night4 int4 NULL,
 night5 int4 NULL,
 night6 int4 NULL,
 night7 int4 NULL,
 night8 int4 NULL,
 night9 int4 NULL,
 night10 int4 NULL,
 CONSTRAINT forecast_moscow_pkey PRIMARY KEY (date)
);

CREATE TABLE predict.forecast_ekaterinburg (
 "date" date NOT NULL,
 day1 int4 NULL,
 day2 int4 NULL,
 day3 int4 NULL,
 day4 int4 NULL,
 day5 int4 NULL,
 day6 int4 NULL,
 day7 int4 NULL,
 day8 int4 NULL,
 day9 int4 NULL,
 day10 int4 NULL,
 night1 int4 NULL,
 night2 int4 NULL,
 night3 int4 NULL,
 night4 int4 NULL,
 night5 int4 NULL,
 night6 int4 NULL,
 night7 int4 NULL,
 night8 int4 NULL,
 night9 int4 NULL,
 night10 int4 NULL,
 CONSTRAINT forecast_ekaterinburg_pkey PRIMARY KEY (date)
);

CREATE TABLE predict.forecast_krasnodar (
 "date" date NOT NULL,
 day1 int4 NULL,
 day2 int4 NULL,
 day3 int4 NULL,
 day4 int4 NULL,
 day5 int4 NULL,
 day6 int4 NULL,
 day7 int4 NULL,
 day8 int4 NULL,
 day9 int4 NULL,
 day10 int4 NULL,
 night1 int4 NULL,
 night2 int4 NULL,
 night3 int4 NULL,
 night4 int4 NULL,
 night5 int4 NULL,
 night6 int4 NULL,
 night7 int4 NULL,
 night8 int4 NULL,
 night9 int4 NULL,
 night10 int4 NULL,
 CONSTRAINT forecast_krasnodar_pkey PRIMARY KEY (date)
);