FROM python:3.11

WORKDIR /app/src/telegram_bot

COPY app/src/core /app/src/core
COPY app/src/telegram_bot /app/src/telegram_bot
COPY DockerBuild/TelegramBot/requirements.txt   .

RUN python -m pip install --upgrade pip && pip install -r requirements.txt
RUN rm requirements.txt

ENV PYTHONUNBUFFERED=1
ENV TZ=Europe/Moscow
ENV PYTHONPATH=/app/src:{$PYTHONPATH}

CMD ["python3", "tg_bot.py"]
